import PrincipalLayout from "@components/layouts/PrincipalLayout";
import AllNotifications from "@components/notifications";
import Head from "next/head";

export default function Notifications() {
  return (
    <>
      <Head>
        <title>Theme</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <AllNotifications />
    </>
  );
}

Notifications.Layout = PrincipalLayout;
