import PrincipalLayout from "@components/layouts/PrincipalLayout"
import Feeds from "@components/middle/feeds";
import Stories from "@components/middle/stories";
import Head from "next/head";
export default function Home(){
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="w-full">
      <Stories/>
      <Feeds/>
      </div>

    </div>
  );
};

Home.Layout = PrincipalLayout;